source 'http://ruby.taobao.org'

gem 'rails', '3.2.9'
gem 'mysql2', '0.3.14'

# Roo provides an interface to Open Office, Excel, and Google Spreadsheets
# https://github.com/Empact/roo
gem 'roo', '~> 2.0.0'
gem 'roo-xls'

# Deploy with Capistrano

group :develop do
  gem 'git-deploy', '0.6.1'
end
