#!/bin/bash

## The MIT License (MIT)
##
## Copyright (c) 2014-2024
## Savin Max <mafei.198@gmail.com>
##
## Permission is hereby granted, free of charge, to any person obtaining a copy
## of this software and associated documentation files (the "Software"), to deal
## in the Software without restriction, including without limitation the rights
## to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
## copies of the Software, and to permit persons to whom the Software is
## furnished to do so, subject to the following conditions:
##
## The above copyright notice and this permission notice shall be included in all
## copies or substantial portions of the Software.
##
## THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
## IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
## FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
## AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
## LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
## OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
## SOFTWARE.

cd ..
CWD=`basename "$PWD"`
cd game_server

host=`hostname -s`
SNAME=game_server
COOKIE=server_local_cookie
SERVER_ENV=development

while getopts ":n:c:e:" o; do
  case "${o}" in
    n)
      SNAME=${OPTARG}
      ;;
    c)
      COOKIE=${OPTARG}
      ;;
    e)
      SERVER_ENV=${OPTARG}
      ;;
  esac
done

echo ""
echo "====================================="
echo "Start daemon server!"
echo "SNAME: $SNAME"
echo "COOKIE: $COOKIE"
echo "SERVER_ENV: $SERVER_ENV"
echo "====================================="
echo ""

SERVER_CONFIG="../$CWD.server.config"

if [ -f $SERVER_CONFIG ]; then
  erl -pa ebin deps/*/ebin \
      -config game_server.config \
      -config ../service.config \
      -config $SERVER_CONFIG \
      -s game_server start $SERVER_ENV \
      -sname "$SNAME@$host" \
      -setcookie $COOKIE \
      -detached \
      +K true
else
  erl -pa ebin deps/*/ebin \
      -config game_server.config \
      -config ../service.config \
      -s game_server start $SERVER_ENV \
      -sname "$SNAME@$host" \
      -setcookie $COOKIE \
      -detached \
      +K true
fi
